FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
FROM python:3.8

RUN sudo apt install git-all
RUN sudo apt install python3-pip

RUN git clone https://github.com/shahyaan/superpoint_transformer.git && \
cd superpoint_transformer"] && \
./install.sh



